""" add problem_id

Revision ID: 2fd46b23f9c4
Revises: 44bc39a5d869
Create Date: 2026-04-13 17:32:53.158703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd46b23f9c4'
down_revision: Union[str, None] = '44bc39a5d869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('problem_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'problem_id')
    # ### end Alembic commands ###
