"""phase_3_init

Revision ID: 44bc39a5d869
Revises: f650c200d11c
Create Date: 2026-04-13 17:14:24.215354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44bc39a5d869'
down_revision: Union[str, None] = 'f650c200d11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mistakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('mistake_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mistakes_id'), 'mistakes', ['id'], unique=False)
    op.create_index(op.f('ix_mistakes_mistake_type'), 'mistakes', ['mistake_type'], unique=False)
    op.create_index(op.f('ix_mistakes_submission_id'), 'mistakes', ['submission_id'], unique=False)
    op.create_index(op.f('ix_mistakes_user_id'), 'mistakes', ['user_id'], unique=False)
    op.add_column('submissions', sa.Column('hints', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'hints')
    op.drop_index(op.f('ix_mistakes_user_id'), table_name='mistakes')
    op.drop_index(op.f('ix_mistakes_submission_id'), table_name='mistakes')
    op.drop_index(op.f('ix_mistakes_mistake_type'), table_name='mistakes')
    op.drop_index(op.f('ix_mistakes_id'), table_name='mistakes')
    op.drop_table('mistakes')
    # ### end Alembic commands ###
